### ISSUE TITLE
🤔

### ISSUE THREAD

**Issue by lulz3xploit** [evildevill/Hackerwasi#8]
I think A "fork" would have been enough... no?

**Comment by evildevill** [comment]
@lulz3xploit iknw but alot of persons can't understand French language

**Comment by lulz3xploit** [comment]
Nobody's complaining about this on LittleBrother. And if that's just why you decided to take over the code, a simple fork and pull requests  of the Translated Text, would have done the case. You just stole the code to take it, and write your name in all source code.

**Comment by h3ckerwasi** [comment]
SoOry it's my mistake i really SoOry for that  I'll give you the credit😐😔
